import React from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, Platform } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import Colors from "@/constants/colors";

const sections = [
  {
    title: "1. Introduction & Scope",
    content: "This Privacy Policy (\"Policy\") is published in accordance with the provisions of the Digital Personal Data Protection Act, 2023 (\"DPDP Act\"), the Information Technology Act, 2000 (\"IT Act\"), the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 (\"IT Rules\"), and Rule 4(1) thereof, and all other applicable laws of India governing the collection, use, storage, and protection of personal data.\n\nGo Bharat 2.0 (\"Go Bharat\", \"Platform\", \"we\", \"us\", or \"our\") is a multi-role hyperlocal super application operated by AASAA PVT. LTD., a company incorporated under the laws of India, with its registered office at Malegaon, Maharashtra 423203, India.\n\nThis Policy applies to all users of the Platform, including but not limited to the following six (6) designated roles:\n\n\u2022 Customers \u2013 individuals who browse, search, and purchase goods and services through the Platform.\n\u2022 Vendors \u2013 businesses and individuals who list, sell, and manage products or services on the Platform.\n\u2022 Delivery Partners \u2013 individuals who accept and fulfill delivery assignments through the Platform.\n\u2022 Marketing Executives \u2013 individuals who onboard vendors, generate leads, and earn commissions through the Platform.\n\u2022 Franchise Owners \u2013 individuals or entities who manage territorial operations and teams on behalf of Go Bharat.\n\u2022 Super Admins \u2013 authorized personnel who administer, manage, and oversee the Platform's operations.\n\nBy accessing, downloading, installing, or using the Go Bharat application or any of its associated services, you acknowledge that you have read, understood, and agree to be bound by this Privacy Policy. If you do not agree with any provision of this Policy, you must immediately cease using the Platform.\n\nThis Platform is intended solely for individuals who are eighteen (18) years of age or older. By using the Platform, you represent and warrant that you are at least 18 years of age and possess the legal capacity to enter into binding agreements under the Indian Contract Act, 1872.",
  },
  {
    title: "2. Definitions",
    content: "For the purposes of this Privacy Policy, the following terms shall have the meanings ascribed to them below:\n\n\u2022 \"Personal Data\" means any data about an individual who is identifiable by or in relation to such data, as defined under Section 2(t) of the DPDP Act, 2023. This includes but is not limited to name, phone number, email address, physical address, and photographs.\n\n\u2022 \"Sensitive Personal Data\" means such personal data as may be classified as sensitive under applicable Indian law, including but not limited to financial information (bank account details, UPI IDs, payment card information), biometric data, health data, and official identifiers (Aadhaar, PAN).\n\n\u2022 \"Data Principal\" means the individual to whom the personal data relates, as defined under Section 2(j) of the DPDP Act, 2023. All users of the Platform in any role are Data Principals with respect to their personal data.\n\n\u2022 \"Data Fiduciary\" means the entity that alone or in conjunction with other persons determines the purpose and means of processing of personal data. AASAA PVT. LTD. is the Data Fiduciary for all personal data processed through the Platform.\n\n\u2022 \"Processing\" means any operation or set of operations performed on personal data, including collection, recording, organization, structuring, storage, adaptation, alteration, retrieval, use, alignment, combination, indexing, sharing, disclosure, restriction, erasure, or destruction thereof.\n\n\u2022 \"Consent\" means a free, specific, informed, unconditional, and unambiguous indication of the Data Principal's wishes by which they, by a clear affirmative action, signify agreement to the processing of their personal data for a specified purpose.\n\n\u2022 \"Data Processor\" means any person or entity who processes personal data on behalf of the Data Fiduciary, including cloud service providers, payment processors, and analytics partners engaged by Go Bharat.\n\n\u2022 \"Third Party\" means any person or entity other than the Data Principal, the Data Fiduciary, and the Data Processor, who may receive personal data in the course of the Platform's operations.\n\n\u2022 \"Cookies\" means small text files placed on your device by the Platform's web version to store user preferences, session information, and analytics data.\n\n\u2022 \"Device Information\" means technical data related to the device used to access the Platform, including but not limited to IP address, device identifier, operating system, browser type, app version, screen resolution, and hardware model.",
  },
  {
    title: "3. Information We Collect",
    content: "Go Bharat collects and processes various categories of personal data to provide, maintain, and improve the Platform's services. The categories of data collected include:\n\n\u2022 Identity Data: Full legal name, date of birth, gender, profile photograph, Aadhaar number (for KYC verification as mandated by applicable law), PAN (Permanent Account Number) for vendors, franchise owners, and other roles requiring tax compliance, and any other government-issued identification documents as may be required.\n\n\u2022 Contact Data: Mobile phone number, email address, residential and/or business addresses, alternate contact numbers, and emergency contact information where applicable.\n\n\u2022 Financial Data: Bank account details (account number, IFSC code, branch name) for vendors, delivery partners, marketing executives, and franchise owners to facilitate payouts and settlements; UPI IDs; digital wallet balance and transaction history; payment method details; GST registration numbers; and invoice and billing records.\n\n\u2022 Location Data: Real-time GPS coordinates for delivery partners during active deliveries; delivery and billing addresses for customers; store/business location for vendors; territory boundaries for franchise owners; and approximate location derived from IP address for all users.\n\n\u2022 Device & Technical Data: IP address, unique device identifiers (IMEI, Advertising ID), operating system type and version, app version and build number, browser type and version, mobile network information, crash logs, diagnostic data, and performance metrics.\n\n\u2022 Usage Data: Browsing and navigation patterns within the Platform, search queries and results, AI-powered search assistant interactions and queries, reel and story viewing history, order patterns and frequency, feature usage statistics, session duration, and referral sources.\n\n\u2022 Content Data: Product reviews and ratings submitted, reels and stories uploaded, community posts and comments, photographs and media uploaded, and any other user-generated content shared on the Platform.\n\n\u2022 Communication Data: Customer support tickets and correspondence, in-app chat messages between users, push notification interaction data, email communications, and feedback and survey responses.",
  },
  {
    title: "4. Role-Specific Data Collection",
    content: "In addition to the general categories of data described above, Go Bharat collects role-specific data tailored to the functions and responsibilities of each user role:\n\n\u2022 Customers: Complete order history including items purchased, quantities, and prices; wishlist and saved items; product and vendor preferences; saved payment methods and instruments; multiple delivery addresses and address labels; coupon and promotional offer redemption history; loyalty points and reward balances; and product return and refund records.\n\n\u2022 Vendors: Business registration documents including Certificate of Incorporation, GST Registration Certificate (under CGST Act, 2017), FSSAI license (for food-related vendors), Shop and Establishment Act license, and Trade License; store details including business name, category, operating hours, and photographs; complete product catalog with pricing, descriptions, and inventory data; sales analytics and revenue data; subscription plan status and billing history; advertisement and promotional campaign bookings; B2B wholesale transaction records; and vendor ratings and performance metrics.\n\n\u2022 Delivery Partners: Vehicle registration details (RC) and vehicle type; valid driving license; real-time GPS tracking data during active delivery assignments (collected continuously from order acceptance to delivery completion); delivery completion rates, average delivery times, and performance scores; earnings statements, incentive records, and payout history; availability status and working hours; and delivery route and distance data.\n\n\u2022 Marketing Executives: Lead generation records including prospective vendor details; vendor onboarding documentation and status; commission earnings, incentive calculations, and payout records; assigned territory and geographic activity data; performance metrics including vendors onboarded, leads converted, and revenue generated; and training and certification records.\n\n\u2022 Franchise Owners: Assigned territory boundaries and demographic data; team management records including executives and delivery partners under supervision; revenue reports, commission structures, and financial statements; performance metrics and KPIs; franchise agreement details and compliance records; and escalation and dispute resolution records.\n\n\u2022 Super Admins: Complete audit logs of all administrative actions performed; system access records including login timestamps, IP addresses, and session durations; configuration changes and platform management activities; user management actions (account approvals, suspensions, role assignments); content moderation decisions and records; and financial oversight and approval records.",
  },
  {
    title: "5. Legal Basis for Processing",
    content: "Go Bharat processes your personal data on one or more of the following lawful bases, as recognized under the DPDP Act, 2023 and other applicable Indian legislation:\n\n\u2022 Consent: Where you have provided free, specific, informed, and unambiguous consent to the processing of your personal data for one or more specified purposes. You may withdraw your consent at any time by contacting our Grievance Officer or through the in-app privacy settings, subject to the provisions of applicable law. Withdrawal of consent shall not affect the lawfulness of processing carried out prior to such withdrawal.\n\n\u2022 Contractual Necessity: Where processing is necessary for the performance of a contract to which you are a party, or to take steps at your request prior to entering into a contract. This includes processing necessary to provide the Platform's services, facilitate transactions, process payments, and coordinate deliveries.\n\n\u2022 Legitimate Interests: Where processing is necessary for the legitimate interests pursued by Go Bharat or a third party, provided such interests are not overridden by your fundamental rights. Legitimate interests include fraud prevention and detection, platform security, service improvement and analytics, enforcement of our Terms of Service, and network and information security.\n\n\u2022 Legal Obligations: Where processing is necessary for compliance with a legal obligation to which Go Bharat is subject, including but not limited to obligations under the CGST Act, 2017 (maintenance of transaction records and tax invoices), the Income Tax Act, 1961 (TDS deductions and financial reporting), the Prevention of Money Laundering Act, 2002 (KYC and suspicious transaction reporting), and any directions or orders issued by competent governmental or regulatory authorities.\n\n\u2022 Vital Interests: Where processing is necessary to protect the vital interests of you or another natural person, including in situations involving threats to life, health, or safety.",
  },
  {
    title: "6. How We Use Your Information",
    content: "Go Bharat uses the personal data collected for the following purposes:\n\n\u2022 Service Delivery: To provide, operate, and maintain the Platform's core services, including processing and fulfilling orders, coordinating deliveries, facilitating payments and settlements, managing user accounts across all roles, and enabling communication between customers, vendors, and delivery partners.\n\n\u2022 Personalization: To customize and enhance your experience on the Platform, including personalized product and vendor recommendations, tailored search results, curated content feeds (reels, stories, community posts), and location-based service suggestions.\n\n\u2022 AI Search Enhancement: To power and improve the Platform's AI-powered search assistant, including processing natural language queries, learning from search interactions to provide more relevant results, and analyzing search patterns to improve the AI model's accuracy and helpfulness.\n\n\u2022 Fraud Prevention & Security: To detect, prevent, and investigate fraudulent transactions, unauthorized access, identity theft, and other illegal or harmful activities on the Platform, including monitoring transaction patterns, verifying user identities, and implementing risk-scoring mechanisms.\n\n\u2022 Analytics & Platform Improvement: To analyze usage patterns, conduct research, and generate insights for improving Platform functionality, user experience, service reliability, and operational efficiency.\n\n\u2022 Marketing & Communications: To send you promotional offers, discounts, new feature announcements, and marketing communications, subject to your explicit opt-in consent. You may opt out of marketing communications at any time through the notification settings in your account or by contacting us directly.\n\n\u2022 Legal Compliance: To comply with applicable laws, regulations, legal processes, or enforceable governmental requests, including tax reporting obligations under the CGST Act, 2017 and the Income Tax Act, 1961.\n\n\u2022 Dispute Resolution: To investigate, mediate, and resolve disputes between users, including order-related disputes, payment disputes, delivery complaints, review authenticity challenges, and any grievances raised through the Platform's redressal mechanism.\n\n\u2022 Platform Integrity: To enforce our Terms of Service, Community Guidelines, and other policies, and to take appropriate action against violations thereof.",
  },
  {
    title: "7. Data Sharing & Disclosure",
    content: "Go Bharat may share your personal data with the following categories of recipients, strictly on a need-to-know basis and in accordance with the principle of data minimization:\n\n\u2022 Vendors: Customer name, delivery address, contact number, and order details are shared with vendors solely for the purpose of order fulfillment and preparation. Vendors are contractually prohibited from using customer data for any purpose other than fulfilling orders placed through the Platform.\n\n\u2022 Delivery Partners: Customer name, delivery address, contact number, and order summary are shared with assigned delivery partners solely for the purpose of executing deliveries. Delivery partner access to customer data is limited to the duration of the active delivery assignment.\n\n\u2022 Payment Processors: Transaction details, including order amounts and payment instrument information, are shared with PCI-DSS compliant payment gateways and banking partners to process payments, settlements, refunds, and payouts securely.\n\n\u2022 Government & Legal Authorities: Personal data may be disclosed to government agencies, law enforcement authorities, regulatory bodies, or courts of competent jurisdiction when required by law, legal process, or governmental request, including pursuant to orders under the IT Act, 2000, directions from the Data Protection Board of India, or requirements under the Code of Criminal Procedure, 1973.\n\n\u2022 Franchise Owners: Territory-level aggregated and anonymized operational data, including order volumes, delivery metrics, and revenue summaries, are shared with franchise owners for territory management and performance monitoring. Individual user data is not shared unless necessary for dispute resolution.\n\n\u2022 Analytics Partners: Anonymized and aggregated usage data may be shared with analytics service providers to analyze Platform performance, user behavior trends, and service quality. Such data is stripped of all personally identifiable information prior to sharing.\n\n\u2022 Service Providers: Technical service providers, including cloud hosting providers, communication service providers, and customer support platforms, may process personal data on behalf of Go Bharat as Data Processors, subject to contractual obligations of confidentiality and data protection.\n\nGo Bharat does NOT sell, rent, lease, trade, or otherwise commercially transfer your personal data to any third party for their independent marketing or advertising purposes. Any sharing of personal data is strictly limited to the purposes described in this Policy and is subject to appropriate contractual safeguards.",
  },
  {
    title: "8. Data Storage & Security",
    content: "Go Bharat implements robust technical and organizational security measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction:\n\n\u2022 Encryption at Rest: All personal data stored on our servers is encrypted using AES-256 (Advanced Encryption Standard with 256-bit keys), which is recognized as a military-grade encryption standard.\n\n\u2022 Encryption in Transit: All data transmitted between your device and our servers is protected using TLS 1.3 (Transport Layer Security version 1.3), ensuring end-to-end encryption of data in transit.\n\n\u2022 Access Controls: Strict role-based access controls (RBAC) are implemented to ensure that only authorized personnel with a legitimate need can access personal data. Multi-factor authentication (MFA) is enforced for all administrative access.\n\n\u2022 Regular Security Audits: We conduct periodic internal and external security audits, vulnerability assessments, and penetration testing to identify and remediate potential security weaknesses.\n\n\u2022 SOC 2 Compliance: Go Bharat is committed to achieving and maintaining SOC 2 Type II compliance, demonstrating our adherence to industry-standard security, availability, processing integrity, confidentiality, and privacy controls.\n\n\u2022 Breach Notification: In the event of a personal data breach, Go Bharat shall notify the Data Protection Board of India within seventy-two (72) hours of becoming aware of the breach, as mandated by the DPDP Act, 2023. Affected Data Principals shall also be notified without undue delay where the breach is likely to result in a high risk to their rights and freedoms.\n\n\u2022 Server Location: All personal data is stored on secure servers located within the territory of India, in compliance with applicable data localization requirements.\n\n\u2022 Backup & Disaster Recovery: Regular automated backups are maintained in geographically distributed, secure data centers within India. A comprehensive disaster recovery plan is in place to ensure business continuity and data availability.\n\n\u2022 Payment Data Security: All payment-related data processing is conducted in a PCI-DSS (Payment Card Industry Data Security Standard) compliant environment. Full credit/debit card numbers are never stored on our servers.",
  },
  {
    title: "9. Data Retention",
    content: "Go Bharat retains your personal data only for as long as necessary to fulfill the purposes for which it was collected, or as required by applicable law. The following retention periods apply:\n\n\u2022 Transaction Records: Financial transaction data, including order details, payment records, invoices, and settlement records, is retained for a minimum period of eight (8) years from the date of the transaction, in compliance with the retention requirements under the CGST Act, 2017 (Section 36 \u2013 six years) and the Income Tax Act, 1961 (Section 149 \u2013 assessment period of up to eight years).\n\n\u2022 Account Data: User profile information and account data is retained for the duration of your active account on the Platform plus an additional three (3) years following account closure or deletion, to address any post-termination claims, disputes, or legal obligations.\n\n\u2022 Delivery GPS Data: Real-time GPS tracking data of delivery partners is retained for a period of ninety (90) days from the date of collection, after which it is permanently anonymized or deleted.\n\n\u2022 Support Tickets: Customer support correspondence, complaint records, and grievance documentation is retained for a period of two (2) years from the date of resolution.\n\n\u2022 KYC Documents: Identity verification documents (Aadhaar, PAN, driving license, business registration) are retained in accordance with the requirements of the Prevention of Money Laundering Act, 2002 and applicable RBI guidelines.\n\n\u2022 Marketing Preferences: Your marketing consent preferences and opt-out records are retained for as long as your account is active and for a period of one (1) year thereafter.\n\n\u2022 Anonymized Data: Anonymized and aggregated data that cannot be used to identify you may be retained indefinitely for analytical, statistical, and research purposes.\n\nUpon expiry of the applicable retention period, personal data is securely deleted or irreversibly anonymized. You may exercise your right to deletion at any time, subject to our obligation to retain certain data under applicable law.",
  },
  {
    title: "10. Cookies & Tracking Technologies",
    content: "Go Bharat uses cookies and similar tracking technologies to enhance your experience on the Platform:\n\n\u2022 Session Cookies: Temporary cookies that are essential for the functioning of the Platform's web version. These cookies maintain your login session, enable shopping cart functionality, and ensure secure navigation. Session cookies are automatically deleted when you close your browser.\n\n\u2022 Persistent Cookies: Cookies that remain on your device for a defined period or until manually deleted. These cookies store your language preferences, login credentials (if you choose \"Remember Me\"), and other customization settings to enhance your return visits.\n\n\u2022 Analytics Cookies: We use anonymized analytics cookies to understand how users interact with the Platform, measure page views, track navigation paths, and identify areas for improvement. Analytics data is aggregated and does not contain personally identifiable information.\n\n\u2022 Advertising Identifiers: On mobile devices, the Platform may access your device's advertising identifier (IDFA on iOS, Advertising ID on Android) to deliver relevant advertisements and measure ad campaign effectiveness. You may reset or limit ad tracking through your device settings.\n\n\u2022 Managing Cookies: You may manage, disable, or delete cookies through your browser settings (for the web version) or device settings (for the mobile application). Please note that disabling essential cookies may impair the functionality of certain features of the Platform.\n\n\u2022 Mobile App Tracking: The Go Bharat mobile application uses device identifiers and analytics SDKs to collect usage data, monitor app performance, and diagnose technical issues. You may opt out of certain tracking through the privacy settings within the application or through your device's operating system settings.\n\n\u2022 Do Not Track: We respect your browser's \"Do Not Track\" (DNT) signal where technically feasible. When a DNT signal is detected, we will limit non-essential tracking activities accordingly.",
  },
  {
    title: "11. Your Rights as Data Principal",
    content: "Under the DPDP Act, 2023, you are entitled to the following rights as a Data Principal with respect to your personal data processed by Go Bharat:\n\n\u2022 Right to Access: You have the right to obtain confirmation as to whether your personal data is being processed by Go Bharat and, if so, to access such personal data along with a summary of the processing activities and the identity of all Data Processors and Third Parties with whom your data has been shared.\n\n\u2022 Right to Correction: You have the right to request the correction of inaccurate or misleading personal data, and the completion of incomplete personal data, without undue delay.\n\n\u2022 Right to Erasure: You have the right to request the erasure of your personal data where it is no longer necessary for the purpose for which it was collected, or where you withdraw your consent, subject to any overriding legal obligations requiring continued retention.\n\n\u2022 Right to Data Portability: You have the right to receive your personal data in a structured, commonly used, and machine-readable format, and to transmit such data to another Data Fiduciary, where technically feasible.\n\n\u2022 Right to Withdraw Consent: Where processing is based on your consent, you have the right to withdraw such consent at any time. Withdrawal of consent shall not affect the lawfulness of processing carried out prior to such withdrawal. You may withdraw consent through the in-app privacy settings or by contacting our Grievance Officer.\n\n\u2022 Right to Grievance Redressal: You have the right to file a grievance with our designated Grievance Officer regarding any aspect of our processing of your personal data. Details of the Grievance Officer are provided in Section 17 of this Policy.\n\n\u2022 Right to Nominate: You have the right to nominate any individual who shall, in the event of your death or incapacity, exercise your rights as Data Principal, in accordance with Section 14 of the DPDP Act, 2023.\n\n\u2022 Right Against Automated Decision-Making: You have the right not to be subject to decisions based solely on automated processing, including profiling, which produce legal effects concerning you or similarly significantly affect you, unless such processing is authorized by law or based on your explicit consent.\n\nTo exercise any of the above rights, please contact our Grievance Officer using the details provided in Section 17 of this Policy. We shall respond to your request within the timeframes prescribed by applicable law.",
  },
  {
    title: "12. Children's Privacy",
    content: "Go Bharat is committed to protecting the privacy of children and minors:\n\n\u2022 The Platform and its services are intended exclusively for individuals who are eighteen (18) years of age or older. By using the Platform, you confirm that you meet this age requirement.\n\n\u2022 Go Bharat does not knowingly collect, solicit, or process personal data from individuals under the age of eighteen (18) years. We do not knowingly allow minors to register for accounts, place orders, or engage in any transactions on the Platform.\n\n\u2022 In the event that a minor requires access to the Platform for any legitimate purpose, such access must be provided under the direct supervision of a parent or legal guardian, who shall provide verifiable consent for any collection and processing of the minor's personal data, in accordance with Section 9 of the DPDP Act, 2023.\n\n\u2022 If we become aware that we have inadvertently collected personal data from a minor without appropriate parental or guardian consent, we shall take immediate steps to delete such data from our records and terminate any associated account.\n\n\u2022 If you are a parent or guardian and believe that your child has provided personal data to Go Bharat without your consent, please contact our Grievance Officer immediately at the details provided in Section 17, and we will take prompt remedial action.",
  },
  {
    title: "13. Cross-Border Data Transfer",
    content: "Go Bharat is committed to compliance with India's data localization requirements:\n\n\u2022 All personal data collected through the Platform is stored and processed on servers located within the territory of India. We do not transfer personal data outside India as a matter of standard practice.\n\n\u2022 In the exceptional circumstance that a cross-border transfer of personal data becomes necessary (for example, to facilitate international payment processing or to engage a foreign service provider), such transfer shall only be made with your explicit consent and to countries or territories that are notified by the Central Government of India as providing adequate protection for personal data, in accordance with Section 16 of the DPDP Act, 2023.\n\n\u2022 Payment Data Localization: In compliance with the Reserve Bank of India's (RBI) directive on Storage of Payment System Data dated April 6, 2018, and subsequent circulars thereto, all payment system data, including full end-to-end transaction details, card data, and payment credentials, is stored exclusively in systems located within India.\n\n\u2022 Where any cross-border transfer is permitted, Go Bharat ensures that appropriate contractual safeguards, including standard contractual clauses and data protection agreements, are in place to protect the confidentiality, integrity, and security of your personal data.\n\n\u2022 Go Bharat shall comply with any directions, restrictions, or conditions imposed by the Central Government of India or the Data Protection Board of India regarding cross-border data transfers.",
  },
  {
    title: "14. Third-Party Links & Services",
    content: "The Platform may contain links to, or integrations with, third-party websites, applications, and services that are not owned or controlled by Go Bharat:\n\n\u2022 Go Bharat is not responsible for the privacy practices, data collection policies, or content of any third-party websites, applications, or services. This Privacy Policy applies solely to personal data collected and processed by Go Bharat through the Platform.\n\n\u2022 Payment Gateways: When you make a payment on the Platform, you may be redirected to a third-party payment gateway. Your interaction with such payment gateways is governed by their respective privacy policies and terms of service. Go Bharat ensures that all payment gateways integrated with the Platform are PCI-DSS compliant.\n\n\u2022 Social Media Integrations: The Platform may allow you to share content or log in using third-party social media services (such as Google, Facebook, or WhatsApp). When you use such integrations, the respective social media platform may collect data about you in accordance with its own privacy policy.\n\n\u2022 Map & Location Services: The Platform utilizes third-party mapping and geolocation services to provide location-based features. Your use of these services is subject to the privacy policies of the respective mapping service providers.\n\n\u2022 We strongly advise you to review the privacy policies of any third-party websites or services before providing any personal data to them. Go Bharat shall not be liable for any loss, damage, or harm arising from your interaction with third-party websites or services.",
  },
  {
    title: "15. AI & Automated Decision-Making",
    content: "Go Bharat employs artificial intelligence (\"AI\") and machine learning technologies to enhance the Platform's services:\n\n\u2022 AI Search Assistant: The Platform features an AI-powered search assistant that processes your natural language queries to deliver relevant search results, product recommendations, and vendor suggestions. The AI search assistant learns from aggregated and anonymized search interactions to improve its accuracy and relevance over time.\n\n\u2022 No Fully Automated Decisions: Go Bharat does not make any fully automated decisions that produce legal effects or similarly significant effects on any Data Principal without human oversight. All material decisions affecting user accounts, vendor approvals, delivery partner onboarding, and dispute resolution involve human review and intervention.\n\n\u2022 Human Oversight: All AI and automated systems deployed on the Platform operate under human supervision. Trained personnel review and oversee automated processes, including content moderation, fraud detection alerts, and algorithmic recommendations.\n\n\u2022 Transparency: Go Bharat is committed to transparency in its use of AI technologies. We will clearly disclose when AI is being used to process your data or influence your experience on the Platform. Users may request information about the logic involved in automated processing that affects them.\n\n\u2022 Algorithmic Fairness: We are committed to ensuring that our AI and algorithmic systems do not discriminate against any individual or group based on race, caste, religion, gender, sexual orientation, disability, or any other protected characteristic. We conduct regular fairness audits of our algorithms.\n\n\u2022 Data Used for AI Training: Aggregated and anonymized usage data may be used to train and improve our AI models. Individual personal data is not used for AI training without explicit consent.",
  },
  {
    title: "16. Breach Notification",
    content: "Go Bharat maintains a comprehensive data breach response plan in accordance with the DPDP Act, 2023:\n\n\u2022 Authority Notification: In the event of a personal data breach, Go Bharat shall notify the Data Protection Board of India within seventy-two (72) hours of becoming aware of such breach, as required under the DPDP Act, 2023. The notification shall include the nature of the breach, the categories and approximate number of Data Principals affected, the likely consequences of the breach, and the measures taken or proposed to be taken to address the breach.\n\n\u2022 User Notification: Where a personal data breach is likely to result in a high risk to the rights and freedoms of affected Data Principals, Go Bharat shall notify such Data Principals without undue delay, through in-app notifications, email, SMS, or other appropriate communication channels. The notification shall describe the nature of the breach and provide recommendations for mitigating potential adverse effects.\n\n\u2022 Remediation Steps: Upon discovery of a data breach, Go Bharat shall immediately take all necessary steps to contain the breach, assess its scope and impact, remediate the vulnerability that caused the breach, and implement measures to prevent recurrence.\n\n\u2022 Investigation Process: Each data breach shall be thoroughly investigated by our security team in coordination with external cybersecurity experts where necessary. A detailed incident report shall be prepared, documenting the root cause, impact assessment, remediation actions, and preventive measures.\n\n\u2022 Record-Keeping: Go Bharat shall maintain a comprehensive record of all personal data breaches, including the facts relating to the breach, its effects, and the remedial action taken, for a period of not less than five (5) years.",
  },
  {
    title: "17. Grievance Redressal",
    content: "In accordance with the provisions of the DPDP Act, 2023 and Rule 5(9) of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, Go Bharat has appointed a Grievance Officer to address your concerns regarding the processing of your personal data:\n\nGrievance Officer Details:\nName: Designated Grievance Officer\nEmail: gobharatservice@gmail.com\nPhone: 8177977700\nAddress: AASAA PVT. LTD., Malegaon, Maharashtra 423203, India\n\n\u2022 Response Time: The Grievance Officer shall acknowledge your grievance within forty-eight (48) hours of receipt.\n\n\u2022 Resolution Time: The Grievance Officer shall investigate and resolve your grievance within thirty (30) days of receipt, in accordance with Rule 5(9) of the IT Rules, 2011.\n\n\u2022 Escalation: If you are not satisfied with the resolution provided by the Grievance Officer, or if your grievance is not resolved within the prescribed timeframe, you have the right to escalate your complaint to the Data Protection Board of India, established under Section 18 of the DPDP Act, 2023.\n\n\u2022 Complaint to Authorities: Nothing in this Policy shall restrict your right to approach any competent court, tribunal, or regulatory authority, including the Data Protection Board of India, the National Consumer Disputes Redressal Commission, or any State Consumer Disputes Redressal Commission, for the redressal of your grievances.\n\n\u2022 In-App Grievance: You may also submit grievances directly through the Help & Support section within the Go Bharat application, which provides a structured grievance submission and tracking mechanism.",
  },
  {
    title: "18. Changes to This Privacy Policy",
    content: "Go Bharat reserves the right to amend, modify, or update this Privacy Policy at any time, at its sole discretion, to reflect changes in our data processing practices, applicable laws, regulatory requirements, or technological developments:\n\n\u2022 Notification of Changes: Any changes to this Privacy Policy shall be communicated to you through a prominent in-app notification, push notification, or email to your registered email address. The updated Policy shall also be made available on the Platform with the revised \"Last Updated\" date.\n\n\u2022 Material Changes: In the event of material changes to this Privacy Policy that substantially affect the way your personal data is collected, used, or shared, Go Bharat shall provide a prominent and conspicuous notice at least fifteen (15) days prior to the effective date of such changes, and shall seek your renewed consent where required by applicable law.\n\n\u2022 Review: We encourage you to periodically review this Privacy Policy to stay informed about how we are protecting your personal data.\n\n\u2022 Continued Use: Your continued use of the Platform after the effective date of any changes to this Privacy Policy shall constitute your acceptance of and agreement to such changes. If you do not agree with any updated provisions, you must discontinue your use of the Platform and may request deletion of your account and personal data.\n\n\u2022 Version History: Previous versions of this Privacy Policy shall be archived and made available upon request to our Grievance Officer.",
  },
  {
    title: "19. Contact Information",
    content: "For any questions, concerns, or requests regarding this Privacy Policy or the processing of your personal data, please contact us through the following channels:\n\nData Protection Officer:\nName: Data Protection Officer, AASAA PVT. LTD.\nEmail: gobharatservice@gmail.com\nPhone: 8177977700\n\nGrievance Officer (appointed under IT Rules, 2011):\nName: Designated Grievance Officer\nEmail: gobharatservice@gmail.com\nPhone: 8177977700\n\nRegistered Office:\nAASAA PVT. LTD.\nMalegaon, Maharashtra 423203\nIndia\n\nGeneral Privacy Inquiries:\nEmail: gobharatservice@gmail.com\nPhone: 8177977700\n\nYou may also reach us through the Help & Support section within the Go Bharat application.\n\nThis Privacy Policy is governed by and construed in accordance with the laws of India. Any disputes arising under or in connection with this Privacy Policy shall be subject to the exclusive jurisdiction of the courts at Malegaon, Maharashtra, India.\n\nThis Privacy Policy was last updated on February 21, 2026, and is effective immediately upon publication.",
  },
];

export default function PrivacyScreen() {
  const insets = useSafeAreaInsets();
  const topInset = Platform.OS === "web" ? 67 : insets.top;
  const bottomInset = Platform.OS === "web" ? 34 : insets.bottom;

  return (
    <View style={styles.container}>
      <LinearGradient colors={["#0B1E3D", "#142F5E"]} style={[styles.header, { paddingTop: topInset + 12 }]}>
        <View style={styles.headerRow}>
          <Pressable onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color="#FFF" />
          </Pressable>
          <Text style={styles.headerTitle}>Privacy Policy</Text>
          <View style={{ width: 40 }} />
        </View>
      </LinearGradient>

      <ScrollView style={styles.content} contentContainerStyle={{ paddingBottom: bottomInset + 20 }} showsVerticalScrollIndicator={false}>
        <Text style={styles.lastUpdated}>Last updated: February 2026</Text>
        {sections.map((section, i) => (
          <View key={i} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionContent}>{section.content}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingBottom: 20, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.1)", alignItems: "center", justifyContent: "center" },
  headerTitle: { fontFamily: "Poppins_600SemiBold", fontSize: 18, color: "#FFF" },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  lastUpdated: { fontFamily: "Poppins_400Regular", fontSize: 12, color: Colors.textLight, marginBottom: 20, textAlign: "center" },
  section: { backgroundColor: "#FFF", borderRadius: 14, padding: 18, marginBottom: 12 },
  sectionTitle: { fontFamily: "Poppins_600SemiBold", fontSize: 15, color: Colors.text, marginBottom: 10 },
  sectionContent: { fontFamily: "Poppins_400Regular", fontSize: 13, color: Colors.textSecondary, lineHeight: 22 },
});
