import React from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, Platform } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import Colors from "@/constants/colors";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: "By downloading, installing, accessing, or using the Go Bharat 2.0 application (\"Platform\"), you unconditionally agree to be legally bound by these Terms and Conditions (\"Terms\") as a binding agreement under the Indian Contract Act, 1872.\n\n\u2022 You must be at least 18 years of age and competent to enter into a legally binding contract under Indian law to use this Platform.\n\n\u2022 If you are accessing or using the Platform on behalf of a business entity, you represent and warrant that you have the authority to bind such entity to these Terms.\n\n\u2022 These Terms are governed exclusively by the laws of India, and any use of the Platform is subject to Indian jurisdiction.\n\n\u2022 If you do not agree with any provision of these Terms, you must immediately cease all use of the Platform and delete your account.\n\n\u2022 Your continued use of the Platform after any modification to these Terms constitutes your irrevocable acceptance of such modifications.\n\n\u2022 These Terms, together with the Privacy Policy and any role-specific agreements, constitute the entire agreement between you and AASAA PVT. LTD.",
  },
  {
    title: "2. Definitions",
    content: "For the purpose of these Terms, the following definitions shall apply:\n\n\u2022 \"Platform\" means the Go Bharat 2.0 mobile application, website, APIs, and all associated services operated by AASAA PVT. LTD.\n\n\u2022 \"Company\", \"We\", \"Us\", \"Our\" refers to AASAA PVT. LTD., a company incorporated under the laws of India, having its registered office in Malegaon, Maharashtra.\n\n\u2022 \"User\" means any individual or entity who accesses or uses the Platform in any capacity, including Customers, Vendors, Delivery Partners, Marketing Executives, Franchise Owners, and Super Admins.\n\n\u2022 \"Customer\" means a registered user who places orders for products or services through the Platform.\n\n\u2022 \"Vendor\" means a business entity or individual registered on the Platform to list, sell, and fulfil orders for products or services.\n\n\u2022 \"Delivery Partner\" means an independent contractor engaged to provide last-mile delivery services through the Platform.\n\n\u2022 \"Marketing Executive\" means an individual authorised by the Platform to conduct field-level marketing, vendor onboarding, and lead generation activities.\n\n\u2022 \"Franchise Owner\" means an individual or entity granted territorial operational rights to manage and grow Go Bharat operations within a designated geographic area.\n\n\u2022 \"Super Admin\" or \"Admin\" means the authorised personnel of AASAA PVT. LTD. with full administrative control over the Platform.\n\n\u2022 \"Content\" means all text, images, videos, reels, stories, reviews, ratings, product listings, advertisements, and any other material uploaded, posted, or transmitted through the Platform.\n\n\u2022 \"Services\" means all features, functionalities, tools, and services provided through the Platform including but not limited to e-commerce, hyperlocal delivery, advertising, wallet services, community features, and B2B services.\n\n\u2022 \"Go Bharat Wallet\" means the digital wallet integrated within the Platform for cashback, refunds, and promotional credits.\n\n\u2022 \"OTP\" means One-Time Password used for verification, authentication, and delivery confirmation purposes.",
  },
  {
    title: "3. User Registration & Account Security",
    content: "All Users must register an account to access the Platform's services. By registering, you agree to the following:\n\n\u2022 Registration requires a valid Indian mobile phone number verified through OTP (One-Time Password). You must have lawful access to the mobile number provided.\n\n\u2022 You must provide accurate, complete, and current information during registration including your full legal name, address, and any other required details. Providing false or misleading information is a violation of these Terms and grounds for immediate account termination.\n\n\u2022 You are solely responsible for maintaining the confidentiality and security of your account credentials, including OTPs, PINs, and passwords.\n\n\u2022 You must not share your account credentials with any third party. Any activity conducted through your account shall be deemed to have been authorised by you.\n\n\u2022 You must not create or operate multiple accounts for the same role. Multi-role access is permitted only where explicitly approved by the Admin and subject to separate verification for each role.\n\n\u2022 You must immediately notify Go Bharat of any unauthorised access to or use of your account. Go Bharat shall not be liable for any loss or damage arising from your failure to comply with this obligation.\n\n\u2022 Go Bharat reserves the right to verify your identity through KYC (Know Your Customer) processes including Aadhaar, PAN, GSTIN, FSSAI license, or other government-issued identification as applicable to your role.\n\n\u2022 Go Bharat may suspend, restrict, or terminate any account at its sole discretion without prior notice if it suspects fraudulent, abusive, or unauthorized activity.",
  },
  {
    title: "4. Platform Usage Rules",
    content: "By using the Platform, you agree to comply with all applicable laws and the following usage rules:\n\n\u2022 You shall use the Platform only for lawful purposes and in compliance with the Information Technology Act, 2000, Consumer Protection Act, 2019, and all other applicable Indian laws and regulations.\n\n\u2022 You shall not attempt to reverse engineer, decompile, disassemble, or otherwise derive the source code, algorithms, or proprietary processes of the Platform.\n\n\u2022 You shall not scrape, crawl, spider, harvest, or use any automated means to access, extract, or collect data or content from the Platform without express written consent.\n\n\u2022 You shall not circumvent, disable, or interfere with any security features, payment mechanisms, commission structures, or fee collection systems of the Platform.\n\n\u2022 You shall not introduce any viruses, malware, trojans, worms, or any other harmful or malicious code into the Platform.\n\n\u2022 You shall not use the Platform to transmit spam, unsolicited communications, or promotional materials outside of authorised channels.\n\n\u2022 You shall not impersonate any person, entity, or Go Bharat representative, or falsely state or misrepresent your affiliation with any person or entity.\n\n\u2022 You shall not engage in any activity that could damage, disable, overburden, or impair the Platform's infrastructure, servers, or networks.\n\n\u2022 You shall not use the Platform to engage in any form of money laundering, terrorist financing, or other financial crimes under the Prevention of Money Laundering Act, 2002.\n\n\u2022 Any violation of these usage rules may result in immediate account suspension, legal action, and reporting to relevant law enforcement authorities.",
  },
  {
    title: "5. Customer Terms",
    content: "The following terms apply specifically to Customers placing orders through the Platform:\n\n\u2022 All orders are subject to availability, Vendor acceptance, and serviceability within the delivery area. Go Bharat does not guarantee the availability of any product or service listed on the Platform.\n\n\u2022 Prices displayed on the Platform are set by Vendors and are inclusive of applicable taxes (GST) unless stated otherwise. Go Bharat may charge delivery fees, platform fees, convenience fees, and surge charges as applicable.\n\n\u2022 Payment can be made via UPI, credit/debit cards, net banking, Go Bharat Wallet, or Cash on Delivery (COD) where available. COD availability is at the sole discretion of Go Bharat and may be restricted based on order value, location, or account history.\n\n\u2022 COD orders exceeding the prescribed limit or from accounts with a history of COD refusals may be blocked. Repeated COD refusals may result in COD privilege revocation or account suspension.\n\n\u2022 Order cancellation is permitted before Vendor confirmation. Once a Vendor has confirmed and begun preparing the order, cancellation charges may apply as determined by the Platform.\n\n\u2022 Returns for non-perishable products are accepted within 7 days of delivery in original condition and packaging. Perishable items (food, grocery, fresh produce) are non-returnable unless damaged, defective, or not as described upon receipt.\n\n\u2022 Refunds for approved returns or cancellations will be credited to your Go Bharat Wallet within 3-5 business days. Original payment method refunds may take 7-14 business days depending on banking processes.\n\n\u2022 Go Bharat Wallet credits are non-transferable, non-withdrawable (unless mandated by regulation), and may carry an expiry period as determined by the Platform.\n\n\u2022 Delivery acceptance requires OTP verification. You must provide the correct OTP to the Delivery Partner to confirm receipt. Failure to provide OTP or accept delivery within the designated time may result in order cancellation and applicable charges.\n\n\u2022 You agree to inspect the order at the time of delivery and report any issues within 24 hours through the Platform's support system.",
  },
  {
    title: "6. Vendor Agreement",
    content: "By registering as a Vendor on the Platform, you agree to the following terms in addition to the general Terms:\n\n\u2022 Vendor onboarding requires payment of a non-refundable onboarding fee as prescribed by Go Bharat at the time of registration. The onboarding fee amount is subject to change at the Admin's discretion.\n\n\u2022 Vendors must subscribe to an active subscription plan to list products and receive orders. Subscription plans are available on Monthly, Quarterly, Half-Yearly, and Annual billing cycles. Plan pricing is determined and may be modified by the Admin.\n\n\u2022 Go Bharat shall deduct a commission on each completed order at the rate prescribed for your product category. Commission rates are set by the Admin and may be revised with 7 days' notice.\n\n\u2022 All product listings must be accurate, truthful, and complete including descriptions, images, prices, weights, dimensions, ingredients, allergens, expiry dates, and any other material information.\n\n\u2022 Pricing on the Platform must comply with MRP regulations and applicable laws. Price gouging, artificial inflation, or deceptive pricing practices are strictly prohibited.\n\n\u2022 Vendors dealing in food products must hold a valid FSSAI (Food Safety and Standards Authority of India) license and comply with the Food Safety and Standards Act, 2006, and all applicable food safety regulations.\n\n\u2022 Vendors must maintain quality standards as prescribed by the Platform. Go Bharat reserves the right to conduct quality audits, mystery shopping, and customer feedback analysis.\n\n\u2022 Vendors shall not directly deal with, solicit, or contact Customers outside the Platform for orders, payments, or services that were initiated through or are related to the Platform.\n\n\u2022 Inventory displayed on the Platform must be accurate and updated in real-time. Repeated order rejections due to stock unavailability may result in penalties, listing deactivation, or account suspension.\n\n\u2022 Vendors must adhere to prescribed packaging standards to ensure product safety and quality during transit. Inadequate packaging resulting in damage shall be the Vendor's liability.\n\n\u2022 By uploading any Content (images, descriptions, videos) to the Platform, you grant Go Bharat a worldwide, royalty-free, perpetual, irrevocable, non-exclusive license to use, reproduce, modify, display, and distribute such Content for Platform operations, marketing, and promotional purposes.\n\n\u2022 Go Bharat reserves the right to delist products, suspend Vendor accounts, or terminate Vendor agreements for quality violations, customer complaints, regulatory non-compliance, or breach of these Terms.",
  },
  {
    title: "7. Delivery Partner Agreement",
    content: "By registering as a Delivery Partner, you acknowledge and agree to the following:\n\n\u2022 You are an independent contractor and NOT an employee, agent, or representative of AASAA PVT. LTD. Nothing in these Terms creates an employer-employee relationship, partnership, joint venture, or agency relationship between you and Go Bharat.\n\n\u2022 You are not entitled to any employment benefits including but not limited to provident fund, ESI, gratuity, paid leave, health insurance, or any other statutory or non-statutory employment benefits.\n\n\u2022 You must maintain a valid driving license, vehicle registration, vehicle insurance, and any other permits required by applicable traffic and transport laws.\n\n\u2022 You must conduct yourself professionally and courteously at all times during deliveries. Rude behaviour, harassment, intoxication, or any misconduct towards Customers, Vendors, or other Users is grounds for immediate deactivation.\n\n\u2022 Delivery confirmation requires OTP verification from the Customer. You must not mark a delivery as complete without obtaining the valid OTP from the Customer.\n\n\u2022 You must complete assigned deliveries in a timely manner and within the estimated delivery window. Persistent delays, order rejections, or low acceptance rates may result in reduced order assignments or account deactivation.\n\n\u2022 You are responsible for the safe handling and transport of goods. You shall be liable for any damage, loss, tampering, or contamination of goods during transit.\n\n\u2022 Earnings are calculated based on the distance, order type, incentives, and other parameters as determined by the Platform. Payout schedules are weekly or as prescribed by the Admin. Go Bharat reserves the right to deduct penalties, damages, or adjustments from your earnings.\n\n\u2022 You are solely responsible for obtaining and maintaining your own health insurance, accident insurance, vehicle insurance, and any other insurance coverage.\n\n\u2022 You shall not solicit Customers or Vendors for services, business, or employment outside the Platform. Any attempt to divert business away from the Platform is a material breach of these Terms.\n\n\u2022 You must comply with all traffic rules, road safety regulations, and applicable laws during the performance of delivery services.",
  },
  {
    title: "8. Marketing Executive Agreement",
    content: "By registering as a Marketing Executive, you agree to the following terms:\n\n\u2022 Your primary duties include field-level lead generation, vendor acquisition, merchant onboarding assistance, promotional activities, and market development within your assigned territory.\n\n\u2022 You must conduct yourself with professionalism and integrity at all times. You represent the Go Bharat brand and must uphold its reputation and values.\n\n\u2022 You shall not make any false promises, misrepresentations, or unauthorised commitments to prospective or existing Vendors regarding commissions, features, pricing, or services of the Platform.\n\n\u2022 Commission and incentive structures for Marketing Executives are determined by the Admin and are subject to change. Commissions are payable only on successful, verified vendor onboarding and sustained vendor activity as per prescribed criteria.\n\n\u2022 You must maintain strict confidentiality of all proprietary information, business strategies, vendor data, customer data, pricing models, and internal processes of Go Bharat. This obligation survives termination of your engagement.\n\n\u2022 During your engagement and for a period of 12 months following termination, you shall not directly or indirectly engage in, solicit for, or compete with Go Bharat in the hyperlocal delivery or e-commerce marketplace space within your assigned territory.\n\n\u2022 You shall not solicit, recruit, or attempt to recruit any Vendors, Delivery Partners, Customers, or other personnel associated with Go Bharat for any competing platform or venture.\n\n\u2022 You must ensure the integrity of the vendor onboarding process. Fraudulent onboarding, ghost vendors, fake registrations, or manipulation of onboarding metrics will result in immediate termination, forfeiture of pending commissions, and potential legal action.\n\n\u2022 You are an independent contractor and not an employee of AASAA PVT. LTD.",
  },
  {
    title: "9. Franchise Owner Agreement",
    content: "By entering into a Franchise arrangement with Go Bharat, you agree to the following:\n\n\u2022 Territory rights granted to Franchise Owners are non-exclusive. Go Bharat reserves the right to appoint additional Franchise Owners, Marketing Executives, or other representatives in the same or overlapping territory.\n\n\u2022 Franchise Owners are responsible for recruiting, managing, training, and supervising their team of Marketing Executives, operational staff, and local support personnel within their territory.\n\n\u2022 Revenue sharing between Franchise Owners and Go Bharat shall be as per the terms agreed in the individual Franchise Agreement. Go Bharat reserves the right to revise revenue sharing percentages with 30 days' written notice.\n\n\u2022 Franchise Owners must strictly comply with Go Bharat brand guidelines including usage of logos, trademarks, colour schemes, marketing materials, and communication standards. Any deviation requires prior written approval.\n\n\u2022 Franchise Owners must maintain prescribed operational standards including response times, vendor onboarding targets, customer satisfaction scores, and quality benchmarks.\n\n\u2022 Franchise Owners must submit accurate and timely reports on operational metrics, financial performance, team activities, and market intelligence as prescribed by the Admin.\n\n\u2022 Sub-franchising is strictly prohibited. Franchise Owners shall not assign, delegate, or transfer their franchise rights, obligations, or territory to any third party without the prior written consent of Go Bharat.\n\n\u2022 Franchise Owners must meet territory performance targets as set by the Admin. Failure to meet targets for two consecutive quarters may result in territory reduction, additional appointments in the territory, or termination of the franchise arrangement.\n\n\u2022 Franchise Owners must ensure that all team members under their supervision comply with Go Bharat's Terms, policies, and code of conduct.\n\n\u2022 The franchise arrangement is terminable by Go Bharat with 30 days' notice or immediately in case of material breach, fraud, or reputational damage.",
  },
  {
    title: "10. Super Admin Rights & Platform Authority",
    content: "AASAA PVT. LTD., through its authorised Super Admin(s), reserves the following rights and authorities:\n\n\u2022 Full and unrestricted administrative control over all aspects of the Platform including features, functionality, design, algorithms, pricing, and policies.\n\n\u2022 The right to modify, amend, update, or replace these Terms and any associated policies at any time and at its sole discretion.\n\n\u2022 The right to suspend, restrict, deactivate, or permanently ban any User account for any reason, including but not limited to violations of these Terms, fraudulent activity, complaints, or quality concerns, with or without prior notice.\n\n\u2022 The right to set, adjust, revise, or remove pricing, commission rates, subscription fees, delivery charges, platform fees, and any other financial parameters.\n\n\u2022 The right to override, reverse, or modify any decision, transaction, order, refund, or dispute resolution outcome.\n\n\u2022 The right to access, review, monitor, and analyse all data generated on or through the Platform including User data, transaction data, communication logs, Content, and operational metrics.\n\n\u2022 The right to generate, export, and utilise reports, analytics, and insights from Platform data for business, operational, legal, or regulatory purposes.\n\n\u2022 The right to manage all User roles including creating, modifying, or revoking role assignments, permissions, and access levels.\n\n\u2022 The right to determine the geographic scope, service areas, and expansion plans of the Platform.\n\n\u2022 The right to enter into, modify, or terminate agreements with any User, partner, or third party.\n\n\u2022 These rights are non-negotiable and inherent to the Platform's operational structure. Users acknowledge and accept these rights as a condition of using the Platform.",
  },
  {
    title: "11. Intellectual Property Rights",
    content: "All intellectual property rights in and to the Platform are owned exclusively by AASAA PVT. LTD.:\n\n\u2022 The Go Bharat name, logo, trademarks, service marks, trade dress, taglines, brand identity, and all associated visual and textual elements are the exclusive property of AASAA PVT. LTD. and are protected under the Trade Marks Act, 1999.\n\n\u2022 All software, source code, algorithms, databases, UI/UX designs, architecture, documentation, and technical innovations underlying the Platform are proprietary to Go Bharat and protected under the Copyright Act, 1957, and the Information Technology Act, 2000.\n\n\u2022 No User shall use, reproduce, modify, distribute, display, or create derivative works from Go Bharat's intellectual property without express written consent.\n\n\u2022 By uploading, posting, or transmitting any Content on the Platform, you grant Go Bharat a worldwide, royalty-free, perpetual, irrevocable, sub-licensable, transferable, non-exclusive license to use, reproduce, modify, adapt, publish, translate, display, distribute, and create derivative works from such Content in any media or format for any business purpose.\n\n\u2022 You represent and warrant that you own or have the necessary rights, licenses, and permissions to all Content you upload to the Platform and that such Content does not infringe upon the intellectual property rights of any third party.\n\n\u2022 Go Bharat respects the intellectual property rights of third parties. If you believe your intellectual property has been infringed, contact us with details of the alleged infringement.\n\n\u2022 Any unauthorised use of Go Bharat's intellectual property may result in legal action including injunctive relief and damages under applicable Indian law.",
  },
  {
    title: "12. Payment Terms & Financial Provisions",
    content: "The following financial terms govern all transactions on the Platform:\n\n\u2022 Go Bharat acts as a payment facilitator and marketplace intermediary. All payments are processed through authorised payment gateways and in compliance with RBI (Reserve Bank of India) guidelines.\n\n\u2022 Go Bharat shall deduct applicable commissions, platform fees, service charges, and any other dues before remitting payouts to Vendors, Delivery Partners, and other payees.\n\n\u2022 All transactions are subject to applicable Goods and Services Tax (GST) as per the CGST Act, 2017, and SGST/IGST as applicable. Go Bharat shall issue tax invoices in compliance with GST regulations.\n\n\u2022 Tax Deducted at Source (TDS) shall be deducted and deposited as required under the Income Tax Act, 1961, including but not limited to Section 194-O for e-commerce transactions.\n\n\u2022 Vendor payouts are processed on a weekly cycle or as specified in the Vendor's subscription plan. Payout processing may take 2-5 business days. Go Bharat reserves the right to withhold payouts in case of disputes, chargebacks, or suspected fraud.\n\n\u2022 Go Bharat Wallet is a closed-loop prepaid instrument. Wallet credits from refunds, cashback, or promotions are subject to expiry, usage restrictions, and terms as determined by the Platform.\n\n\u2022 Refund processing timelines vary by payment method: Wallet refunds are instant; UPI refunds take 2-5 business days; card/netbanking refunds take 7-14 business days.\n\n\u2022 In case of chargebacks initiated by customers through their bank or card issuer, Go Bharat reserves the right to recover the disputed amount from the Vendor's pending payouts.\n\n\u2022 Go Bharat charges a non-refundable platform service fee on each transaction, the rate of which is determined and may be modified by the Admin.\n\n\u2022 Users are responsible for all applicable taxes, duties, and regulatory compliance related to their income, sales, and transactions on the Platform.",
  },
  {
    title: "13. Data Protection & Privacy",
    content: "Go Bharat is committed to protecting your personal data and privacy:\n\n\u2022 Your use of the Platform is governed by our Privacy Policy, which forms an integral part of these Terms. Please read the Privacy Policy carefully.\n\n\u2022 Go Bharat collects and processes personal data in compliance with the Digital Personal Data Protection Act, 2023 (DPDP Act), the Information Technology Act, 2000, and the IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011.\n\n\u2022 By using the Platform, you provide explicit consent for the collection, storage, processing, and use of your personal data including name, mobile number, email, address, location data, device information, transaction history, and behavioural data.\n\n\u2022 Personal data is processed for the purposes of service delivery, order fulfilment, payment processing, customer support, fraud prevention, analytics, marketing communications, and regulatory compliance.\n\n\u2022 Go Bharat shall not transfer personal data outside India unless such transfer complies with the provisions of the DPDP Act, 2023, and applicable data protection regulations.\n\n\u2022 You have the right to access, correct, update, and request deletion of your personal data subject to legal and contractual obligations. Data deletion requests may be subject to mandatory retention periods under applicable law.\n\n\u2022 Go Bharat implements reasonable security measures to protect personal data from unauthorised access, disclosure, alteration, or destruction. However, no system is completely secure, and Go Bharat does not guarantee absolute data security.\n\n\u2022 Go Bharat may share data with law enforcement agencies, regulatory authorities, or judicial bodies as required by law or legal process.",
  },
  {
    title: "14. Content Guidelines & Moderation",
    content: "All Content uploaded, posted, or shared on the Platform must comply with the following guidelines:\n\n\u2022 Content must not contain or promote violence, hatred, discrimination, obscenity, pornography, defamation, or any material that is illegal under Indian law.\n\n\u2022 Content must not infringe upon the intellectual property rights, privacy rights, or any other rights of any third party.\n\n\u2022 Content must not contain false, misleading, deceptive, or fraudulent information.\n\n\u2022 Reels, stories, and community posts must comply with community standards. Content depicting or promoting illegal activities, substance abuse, self-harm, dangerous challenges, or hate speech shall be immediately removed.\n\n\u2022 Product reviews and ratings must be genuine, based on actual purchase and experience. Fake reviews, paid reviews (outside Platform programs), review manipulation, or review bombing are strictly prohibited.\n\n\u2022 Go Bharat reserves the right to moderate, edit, remove, or refuse to publish any Content at its sole discretion and without prior notice or explanation.\n\n\u2022 Go Bharat may use automated systems and manual review processes for content moderation. Decisions of the moderation team are final.\n\n\u2022 Repeated violations of content guidelines may result in Content restrictions, account suspension, or permanent ban.\n\n\u2022 Go Bharat shall not be liable for any User-generated Content and does not endorse, guarantee, or assume responsibility for the accuracy or reliability of such Content.\n\n\u2022 Content guidelines are subject to modification at the Admin's discretion, and Users are responsible for staying updated on current guidelines.",
  },
  {
    title: "15. Limitation of Liability",
    content: "To the maximum extent permitted by applicable law, the following limitations apply:\n\n\u2022 Go Bharat operates as a marketplace facilitator and technology platform under Section 2(45) of the Consumer Protection Act, 2019. Go Bharat is NOT a seller, manufacturer, or service provider for products and services listed by Vendors.\n\n\u2022 Go Bharat does not warrant the quality, safety, legality, merchantability, or fitness for a particular purpose of any product or service listed on the Platform.\n\n\u2022 Go Bharat shall not be liable for any direct, indirect, incidental, special, consequential, punitive, or exemplary damages, including but not limited to damages for loss of profits, goodwill, data, or other intangible losses.\n\n\u2022 The total aggregate liability of Go Bharat to any User for any claims arising out of or related to the Platform shall not exceed the total fees paid by such User to Go Bharat in the 3 months immediately preceding the event giving rise to the claim.\n\n\u2022 Go Bharat shall not be liable for any delay, failure, or interruption of service resulting from Force Majeure events as defined in these Terms.\n\n\u2022 Go Bharat shall not be liable for any acts or omissions of Vendors, Delivery Partners, Marketing Executives, Franchise Owners, or any third party.\n\n\u2022 Go Bharat does not guarantee uninterrupted, error-free, or secure access to the Platform. The Platform is provided on an \"AS IS\" and \"AS AVAILABLE\" basis without warranties of any kind.\n\n\u2022 Users acknowledge that they use the Platform at their own risk and discretion.",
  },
  {
    title: "16. Indemnification",
    content: "You agree to indemnify, defend, and hold harmless AASAA PVT. LTD., its directors, officers, employees, agents, affiliates, and partners from and against any and all claims, demands, actions, suits, proceedings, losses, damages, liabilities, costs, and expenses (including reasonable attorney fees) arising out of or related to:\n\n\u2022 Your use or misuse of the Platform.\n\n\u2022 Your breach of any provision of these Terms or any applicable law.\n\n\u2022 Your violation of any rights of any third party, including intellectual property, privacy, or contractual rights.\n\n\u2022 Any Content you upload, post, or transmit through the Platform.\n\n\u2022 Your negligence, fraud, wilful misconduct, or illegal activities.\n\n\u2022 Any product or service you sell, deliver, or provide through the Platform (applicable to Vendors and Delivery Partners).\n\n\u2022 Any tax liability, regulatory penalty, or compliance failure attributable to you.\n\n\u2022 Any claim by a third party related to your activities on or through the Platform.\n\n\u2022 This indemnification obligation shall survive the termination of your account and these Terms.",
  },
  {
    title: "17. Dispute Resolution & Arbitration",
    content: "Any dispute, controversy, or claim arising out of or relating to these Terms or the Platform shall be resolved as follows:\n\n\u2022 The parties shall first attempt to resolve any dispute through good-faith negotiation. You must send a written notice of dispute to Go Bharat, describing the nature of the claim and the relief sought, at least 30 days before initiating any formal proceedings.\n\n\u2022 If the dispute is not resolved through negotiation within 30 days, it shall be referred to and finally resolved by binding arbitration in accordance with the Arbitration and Conciliation Act, 1996, as amended.\n\n\u2022 The seat and venue of arbitration shall be Nashik, Maharashtra, India. The language of arbitration shall be English.\n\n\u2022 The arbitration shall be conducted by a sole arbitrator appointed by Go Bharat. The arbitrator's decision shall be final and binding on both parties.\n\n\u2022 Each party shall bear its own costs of arbitration unless the arbitrator orders otherwise.\n\n\u2022 You agree that any dispute resolution proceedings will be conducted only on an individual basis and NOT as a class action, collective action, or representative action. You hereby waive any right to participate in class action lawsuits or class-wide arbitration.\n\n\u2022 Notwithstanding the above, Go Bharat reserves the right to seek injunctive or equitable relief in any court of competent jurisdiction to protect its intellectual property rights or to prevent irreparable harm.\n\n\u2022 For claims below Rs. 10,00,000 (Ten Lakhs), the dispute shall first be submitted to the Platform's internal grievance redressal mechanism before proceeding to arbitration.",
  },
  {
    title: "18. Termination",
    content: "Go Bharat reserves the right to terminate, suspend, or restrict any User's access to the Platform:\n\n\u2022 Go Bharat may terminate any User account at its sole discretion, with or without cause, and with or without prior notice.\n\n\u2022 Users may request account termination by contacting Go Bharat support. Account termination requests are subject to settlement of all pending obligations, dues, and liabilities.\n\n\u2022 Upon termination, the User's right to access and use the Platform shall immediately cease. All licenses granted to the User under these Terms shall be revoked.\n\n\u2022 Pending payouts to Vendors and Delivery Partners shall be processed within 30 days of termination, subject to deduction of any outstanding dues, penalties, chargebacks, or damages.\n\n\u2022 Go Bharat shall retain User data for a period as required by applicable law, regulatory requirements, or legitimate business purposes, even after account termination.\n\n\u2022 The following provisions shall survive termination of these Terms: Intellectual Property, Indemnification, Limitation of Liability, Dispute Resolution, Confidentiality, Data Retention, and any other provisions that by their nature should survive termination.\n\n\u2022 Termination of your account does not relieve you of any obligations, liabilities, or dues incurred prior to termination.\n\n\u2022 Go Bharat shall not be liable to any User for any termination, suspension, or restriction of access to the Platform.",
  },
  {
    title: "19. Advertising & Deals",
    content: "Go Bharat offers advertising and promotional opportunities on the Platform subject to the following terms:\n\n\u2022 Ad slot bookings and daily deal slot promotions are available to Vendors at rates determined by the Admin. Pricing for advertising slots may vary based on placement, duration, category, and demand.\n\n\u2022 All advertising and deal slot booking fees are non-refundable once the booking is confirmed, regardless of whether the ad or deal achieves the desired results.\n\n\u2022 All advertisements and promotional content are subject to review and approval by Go Bharat. Go Bharat reserves the right to reject, modify, or remove any advertisement that does not comply with content guidelines, legal requirements, or brand standards.\n\n\u2022 Advertisements must be truthful, non-deceptive, and comply with the Advertising Standards Council of India (ASCI) guidelines, Consumer Protection Act, 2019, and all applicable advertising regulations.\n\n\u2022 Go Bharat does not guarantee any specific results, impressions, clicks, conversions, or sales from advertising or deal placements.\n\n\u2022 Go Bharat reserves the right to modify advertising rates, slot availability, placement algorithms, and promotional terms at any time.\n\n\u2022 Sponsored content and advertisements will be appropriately labelled as such on the Platform.",
  },
  {
    title: "20. Prohibited Activities",
    content: "The following activities are strictly prohibited on the Platform. Violation may result in immediate account termination, forfeiture of funds, and legal action:\n\n\u2022 Fraud: Engaging in any fraudulent activity including fake orders, fraudulent refund claims, payment fraud, identity theft, or financial manipulation.\n\n\u2022 Impersonation: Impersonating any person, User, Vendor, Delivery Partner, Admin, or Go Bharat representative.\n\n\u2022 Manipulation: Manipulating prices, ratings, reviews, search results, algorithms, or any Platform feature for unfair advantage.\n\n\u2022 Fake Reviews: Writing, soliciting, purchasing, or incentivising fake reviews or ratings. Review bombing or targeted negative review campaigns against competitors.\n\n\u2022 Price Gouging: Artificially inflating prices during high-demand periods, emergencies, or natural disasters in violation of applicable pricing regulations.\n\n\u2022 Data Harvesting: Collecting, scraping, mining, or harvesting personal data, contact information, or business data of Users, Vendors, or Customers from the Platform.\n\n\u2022 Spam: Sending unsolicited messages, notifications, promotional materials, or communications to Users through or outside the Platform.\n\n\u2022 Harassment: Engaging in harassment, threats, bullying, stalking, or abusive behaviour towards any User, Vendor, Delivery Partner, or Go Bharat personnel.\n\n\u2022 Competitive Intelligence: Using the Platform to gather competitive intelligence, market data, or business information for the benefit of a competing platform or business.\n\n\u2022 Circumvention: Attempting to circumvent Platform fees, commissions, payment systems, or security measures.\n\n\u2022 Money Laundering: Using the Platform for money laundering, terrorist financing, or any financial crime.\n\n\u2022 Counterfeit Goods: Listing, selling, or delivering counterfeit, pirated, stolen, or illegal goods through the Platform.\n\n\u2022 Multi-accounting: Creating multiple accounts to exploit promotions, referral programs, or to circumvent account restrictions.\n\n\u2022 Platform Abuse: Exploiting bugs, vulnerabilities, or system errors for personal gain instead of reporting them to Go Bharat.",
  },
  {
    title: "21. Modifications to Terms",
    content: "Go Bharat reserves the right to modify these Terms at any time:\n\n\u2022 Go Bharat may modify, amend, supplement, or replace these Terms at any time and at its sole discretion.\n\n\u2022 Notifications of changes to these Terms will be communicated through the Platform via in-app notifications, push notifications, or email.\n\n\u2022 Your continued use of the Platform after modifications are posted constitutes your binding acceptance of the revised Terms.\n\n\u2022 For material changes that significantly affect your rights or obligations, Go Bharat will provide at least 15 days' advance notice before such changes take effect.\n\n\u2022 If you do not agree with any modifications, your sole remedy is to discontinue use of the Platform and close your account before the changes take effect.\n\n\u2022 It is your responsibility to review these Terms periodically to stay informed of any changes.\n\n\u2022 The most current version of these Terms will always be available within the Platform.",
  },
  {
    title: "22. Governing Law & Jurisdiction",
    content: "These Terms and your use of the Platform are governed by the following:\n\n\u2022 These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles.\n\n\u2022 Subject to the arbitration clause in Section 17, the courts of Malegaon, District Nashik, Maharashtra, India shall have exclusive jurisdiction over any disputes arising from these Terms or the use of the Platform.\n\n\u2022 For matters requiring appellate jurisdiction, the High Court of Bombay (Bench at Aurangabad or Mumbai) and the Supreme Court of India shall have jurisdiction.\n\n\u2022 These Terms are subject to the provisions of the Indian Contract Act, 1872; Information Technology Act, 2000; Consumer Protection Act, 2019; Digital Personal Data Protection Act, 2023; and all other applicable Indian statutes and regulations.\n\n\u2022 Users irrevocably submit to the jurisdiction of the courts specified herein and waive any objection to venue or inconvenient forum.",
  },
  {
    title: "23. Severability & Waiver",
    content: "The following provisions ensure the enforceability of these Terms:\n\n\u2022 If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be severed from these Terms and the remaining provisions shall continue in full force and effect.\n\n\u2022 The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving the original intent of the parties.\n\n\u2022 The failure of Go Bharat to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.\n\n\u2022 Any waiver of any provision of these Terms shall be effective only if made in writing and signed by an authorised representative of Go Bharat.\n\n\u2022 A waiver of any right or provision on one occasion shall not be deemed a waiver of such right or provision on any subsequent occasion.",
  },
  {
    title: "24. Force Majeure",
    content: "Go Bharat shall not be liable for any failure or delay in performing its obligations under these Terms due to Force Majeure events:\n\n\u2022 Force Majeure events include but are not limited to: natural disasters (floods, earthquakes, cyclones, droughts), epidemics, pandemics, acts of God, war, terrorism, civil unrest, riots, strikes, lockouts, government actions, regulatory changes, power failures, internet disruptions, cyberattacks, and any other events beyond the reasonable control of Go Bharat.\n\n\u2022 In the event of a Force Majeure, Go Bharat's obligations shall be suspended for the duration of the Force Majeure event without any liability.\n\n\u2022 Go Bharat shall make reasonable efforts to notify affected Users of the Force Majeure event and its expected duration.\n\n\u2022 If a Force Majeure event continues for more than 90 days, Go Bharat may terminate affected agreements or services without liability.\n\n\u2022 Force Majeure shall not relieve Users of their payment obligations for services already rendered or products already delivered.",
  },
  {
    title: "25. Contact Information",
    content: "For any questions, concerns, grievances, or legal notices regarding these Terms and Conditions, please contact us at:\n\n\u2022 Registered Entity: AASAA PVT. LTD.\n\n\u2022 Email: gobharatservice@gmail.com\n\n\u2022 Phone: 8177977700\n\n\u2022 Registered Address: AASAA PVT. LTD., Malegaon, District Nashik, Maharashtra 423203, India\n\n\u2022 Grievance Officer: As required under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the details of the Grievance Officer are available within the Platform under the Help & Support section.\n\n\u2022 Grievance redressal timeline: All grievances shall be acknowledged within 24 hours and resolved within 15 days of receipt as per applicable regulations.\n\n\u2022 Support Hours: Monday to Saturday, 9:00 AM to 9:00 PM IST.\n\n\u2022 For legal notices: Legal Department, AASAA PVT. LTD., Malegaon, District Nashik, Maharashtra 423203, India.",
  },
];

export default function TermsScreen() {
  const insets = useSafeAreaInsets();
  const topInset = Platform.OS === "web" ? 67 : insets.top;
  const bottomInset = Platform.OS === "web" ? 34 : insets.bottom;

  return (
    <View style={styles.container}>
      <LinearGradient colors={["#0B1E3D", "#142F5E"]} style={[styles.header, { paddingTop: topInset + 12 }]}>
        <View style={styles.headerRow}>
          <Pressable onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color="#FFF" />
          </Pressable>
          <Text style={styles.headerTitle}>Terms & Conditions</Text>
          <View style={{ width: 40 }} />
        </View>
      </LinearGradient>

      <ScrollView style={styles.content} contentContainerStyle={{ paddingBottom: bottomInset + 20 }} showsVerticalScrollIndicator={false}>
        <Text style={styles.lastUpdated}>Last updated: February 2026</Text>
        {sections.map((section, i) => (
          <View key={i} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionContent}>{section.content}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingBottom: 20, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.1)", alignItems: "center", justifyContent: "center" },
  headerTitle: { fontFamily: "Poppins_600SemiBold", fontSize: 18, color: "#FFF" },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  lastUpdated: { fontFamily: "Poppins_400Regular", fontSize: 12, color: Colors.textLight, marginBottom: 20, textAlign: "center" },
  section: { backgroundColor: "#FFF", borderRadius: 14, padding: 18, marginBottom: 12 },
  sectionTitle: { fontFamily: "Poppins_600SemiBold", fontSize: 15, color: Colors.text, marginBottom: 10 },
  sectionContent: { fontFamily: "Poppins_400Regular", fontSize: 13, color: Colors.textSecondary, lineHeight: 22 },
});
