import { createContext, useContext } from "react";
import { User, CartItem, Order, Address, WalletTransaction, Lead, UserRole, Vendor, VendorApplication, VendorAppStatus, Reel, ReelComment, AdminCoupon, BannedUser, Notification, TeamMember, Review, SubCategory, Category, AdRequest, AdStatus, CustomerStory, CommunityPost, CommunityComment, VendorFollow, FeatureFlag, DynamicPage, AppAnnouncement, DealBooking, DealBookingStatus, DealSlotDuration, AdminPricing, LiveSession, LiveChatMessage, Invoice, InvoiceType, CoinTransaction, CoinTransactionType, HomeBanner, HomeDeal, PromoMedia } from "./types";
import { BusRoute } from "./data";
import { Language } from "./i18n";

export interface AppState {
  initialized: boolean;
  user: User | null;
  isAuthenticated: boolean;
  language: Language;
  autoDetectLanguage: boolean;
  setLanguage: (lang: Language) => void;
  setAutoDetectLanguage: (auto: boolean) => void;
  cart: CartItem[];
  orders: Order[];
  addresses: Address[];
  walletBalance: number;
  walletTransactions: WalletTransaction[];
  leads: Lead[];
  vendorOrders: Order[];
  deliveryOrders: Order[];
  isOnline: boolean;
  vendorApplications: VendorApplication[];
  liveVendors: Vendor[];
  customerPinCode: string;
  setCustomerPinCode: (pin: string) => void;
  reloadVendors: () => void;
  loadHomeContent: () => Promise<void>;
  refreshAdRequests: () => Promise<void>;
  reels: Reel[];
  adminCoupons: AdminCoupon[];
  bannedUsers: BannedUser[];
  notifications: Notification[];
  teamMembers: TeamMember[];
  customSubCategories: SubCategory[];
  liveCategories: Category[];
  liveSubCategories: SubCategory[];
  liveBusRoutes: BusRoute[];
  reviews: Review[];
  addReview: (review: Omit<Review, "id" | "createdAt" | "helpful">) => void;
  markReviewHelpful: (reviewId: string) => void;
  adRequests: AdRequest[];
  submitAdRequest: (ad: Omit<AdRequest, "id" | "status" | "createdAt">) => void;
  reviewAdRequestFranchise: (adId: string, approved: boolean, reason?: string) => void;
  reviewAdRequestAdmin: (adId: string, approved: boolean, reason?: string) => void;
  makeAdLive: (adId: string) => void;
  customerStories: CustomerStory[];
  addCustomerStory: (story: Omit<CustomerStory, "id" | "likes" | "isLiked" | "isFeatured" | "createdAt">) => void;
  toggleStoryLike: (storyId: string) => void;
  toggleStoryFeatured: (storyId: string) => void;
  deleteCustomerStory: (storyId: string) => void;
  communityPosts: CommunityPost[];
  communityComments: CommunityComment[];
  vendorFollows: VendorFollow[];
  addCommunityPost: (post: Omit<CommunityPost, "id" | "likes" | "isLiked" | "commentsCount" | "createdAt">) => void;
  togglePostLike: (postId: string) => void;
  addPostComment: (postId: string, text: string) => void;
  followVendor: (vendorId: string, vendorName: string) => void;
  unfollowVendor: (vendorId: string) => void;
  isFollowingVendor: (vendorId: string) => boolean;
  adminPhone: string;
  setAdminPhone: (phone: string) => void;
  getRegisteredMember: (phone: string) => TeamMember | undefined;
  login: (phone: string, role: UserRole) => void;
  logout: () => void;
  addToCart: (item: CartItem) => void;
  removeFromCart: (productId: string) => void;
  updateCartQuantity: (productId: string, quantity: number) => void;
  clearCart: () => void;
  placeOrder: (address: string, deliveryNote?: string, deliverySpeed?: "express" | "standard" | "scheduled", seatSelections?: Record<string, { label: string; class?: string }>, paidTotal?: number, paymentInfo?: { method?: Order["paymentMethod"]; status?: Order["paymentStatus"] }) => Order;
  updateOrderStatus: (orderId: string, status: Order["status"]) => void;
  acceptDelivery: (orderId: string) => void;
  addAddress: (address: Omit<Address, "id">) => string;
  removeAddress: (addressId: string) => void;
  setDefaultAddress: (addressId: string) => void;
  addWalletMoney: (amount: number) => void;
  deductWallet: (amount: number, reference: string) => boolean;
  applyAuthoritativeWalletDebit: (newBalance: number, amount: number, reference: string) => void;
  toggleOnline: () => void;
  addLead: (lead: Omit<Lead, "id" | "createdAt">) => void;
  updateLeadStatus: (leadId: string, status: Lead["status"]) => void;
  submitVendorApplication: (app: Omit<VendorApplication, "id" | "status" | "submittedAt" | "submittedBy">) => Promise<boolean | string>;
  reviewVendorApplication: (appId: string, status: VendorAppStatus, rejectionReason?: string) => Promise<boolean>;
  makeVendorLive: (appId: string) => Promise<boolean>;
  bulkApproveVendors: () => Promise<{ ok: boolean; approved: number }>;
  deleteVendor: (id: string) => Promise<boolean>;
  addReel: (reel: Omit<Reel, "id" | "likes" | "comments" | "shares" | "isLiked" | "createdAt">) => void;
  toggleReelLike: (reelId: string) => void;
  deleteReel: (reelId: string) => void;
  reelComments: ReelComment[];
  addReelComment: (reelId: string, text: string) => void;
  addAdminCoupon: (coupon: Omit<AdminCoupon, "id" | "usedCount" | "createdAt">) => void;
  toggleAdminCoupon: (couponId: string) => void;
  deleteAdminCoupon: (couponId: string) => void;
  banUser: (user: Omit<BannedUser, "id" | "bannedAt">) => void;
  unbanUser: (bannedId: string) => void;
  sendNotification: (notif: Omit<Notification, "id" | "sentAt" | "read">) => void;
  markNotificationRead: (notifId: string) => void;
  markAllNotificationsRead: (role: UserRole) => void;
  readNotifIds: string[];
  markNotifItemsRead: (ids: string[]) => void;
  cancelOrder: (orderId: string) => void;
  refundOrder: (orderId: string) => void;
  confirmQrPayment: (orderId: string) => Promise<boolean>;
  rejectQrPayment: (orderId: string) => Promise<boolean>;
  addTeamMember: (member: Omit<TeamMember, "id" | "createdAt">) => void;
  removeTeamMember: (memberId: string) => void;
  toggleTeamMemberStatus: (memberId: string) => void;
  editTeamMember: (memberId: string, updates: Partial<Pick<TeamMember, "name" | "phone" | "email" | "city" | "role" | "territory" | "bankName" | "accountNumber" | "ifscCode" | "accountHolderName">>) => Promise<boolean>;
  addSubCategory: (subCat: Omit<SubCategory, "id">) => void;
  removeSubCategory: (subCatId: string) => void;
  replyToReview: (reviewId: string, reply: string) => void;
  deleteReview: (reviewId: string) => void;
  deleteCommunityPost: (postId: string) => void;
  deletePostComment: (commentId: string, postId: string) => void;
  togglePinPost: (postId: string) => void;
  toggleHidePost: (postId: string) => void;
  featureFlags: FeatureFlag[];
  dynamicPages: DynamicPage[];
  appAnnouncements: AppAnnouncement[];
  isFeatureEnabled: (featureName: string) => boolean;
  refreshAppConfig: () => Promise<void>;
  dealBookings: DealBooking[];
  adminPricing: AdminPricing;
  submitDealBooking: (booking: Omit<DealBooking, "id" | "status" | "createdAt" | "slotFee">) => Promise<void>;
  reviewDealBooking: (bookingId: string, approved: boolean, reason?: string) => void;
  updateAdminPricing: (pricing: Partial<AdminPricing>) => void;
  unreadNotificationCount: number;
  termsAcceptedRoles: string[];
  acceptTermsForRole: (role: UserRole) => void;
  hasAcceptedTerms: (role: UserRole) => boolean;
  liveSessions: LiveSession[];
  startLiveSession: (session: Omit<LiveSession, "id" | "viewers" | "peakViewers" | "likes" | "isLiked" | "status" | "startedAt" | "chatMessages">) => LiveSession;
  endLiveSession: (sessionId: string) => void;
  addLiveChatMessage: (sessionId: string, message: string) => void;
  likeLiveSession: (sessionId: string) => void;
  joinLiveSession: (sessionId: string) => void;
  leaveLiveSession: (sessionId: string) => void;
  invoices: Invoice[];
  getInvoiceByRef: (referenceId: string) => Invoice | undefined;
  addInvoice: (invoice: Invoice) => void;
  vendorProfileImages: Record<string, string>;
  updateVendorProfileImage: (imageUri: string, imageBase64?: string) => void;
  removeVendorProfileImage: () => void;
  updateVendorPaymentQr: (imageBase64: string) => Promise<boolean>;
  removeVendorPaymentQr: () => Promise<boolean>;
  vendorCodSettings: Record<string, boolean>;
  updateVendorCod: (vendorId: string, enabled: boolean) => void;
  toggleVendorOpen: (vendorId: string, isOpen: boolean) => Promise<void>;
  coinBalance: number;
  coinTransactions: CoinTransaction[];
  addCoins: (amount: number, reference: string, type: CoinTransactionType) => void;
  redeemCoins: (amount: number, reference: string) => boolean;
  redeemCoinsToWallet: (coins: number) => Promise<{ success: boolean; error?: string; rupees?: number; newWalletBalance?: number; newCoinBalance?: number }>;
  purchaseCoins: (amount: number) => void;
  homeBanners: HomeBanner[];
  homeDeals: HomeDeal[];
  addHomeBanner: (banner: Omit<HomeBanner, "id" | "createdAt">) => Promise<void>;
  updateHomeBanner: (id: string, updates: Partial<HomeBanner>) => Promise<void>;
  deleteHomeBanner: (id: string) => Promise<void>;
  addHomeDeal: (deal: Omit<HomeDeal, "id" | "createdAt">) => Promise<void>;
  updateHomeDeal: (id: string, updates: Partial<HomeDeal>) => Promise<void>;
  deleteHomeDeal: (id: string) => Promise<void>;
  promoMedia: PromoMedia[];
  addPromoMedia: (item: Omit<PromoMedia, "id" | "createdAt">) => Promise<void>;
  removePromoMedia: (id: string) => Promise<void>;
  togglePromoMedia: (id: string, isActive: boolean) => Promise<void>;
  showGuestLoginPrompt: boolean;
  setShowGuestLoginPrompt: (show: boolean) => void;
  lastOrderStatusChange: number;
}

export const AppContext = createContext<AppState | null>(null);

export function useApp(): AppState {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within AppProvider");
  }
  return context;
}
